### ISSUE TITLE
很感谢大佬的分享，全网最详细的讲解

### ISSUE THREAD

**Issue by Jolray** [luzhixing12345/xiaohongshu-spider#1]
我按照您的代码运行，包也都安装了，但是运行之后只显示“配置文件正常”，没有其他反映，就退出了，pyautogui并不会操纵我的键鼠，小白，麻烦大佬指点一下，谢谢！！
![Uploading image.png…]()

**Comment by luzhixing12345** [comment]
您好，这是一个bug，pyautogui由于不同电脑屏幕分辨率不同导致图片识别出现问题。我仅在我电脑上通过了验证未注意到这个问题，我稍后修改一下解决这个问题，不好意思

**Comment by luzhixing12345** [comment]
bug已修复
