### ISSUE TITLE
只能支持windows吗？Mac很难运行

### ISSUE THREAD

**Issue by neohob** [luzhixing12345/xiaohongshu-spider#5]
Mac上把所有包都装了以后，自动点击输入都是无法正常运行的

**Comment by luzhixing12345** [comment]
你好，我本机开发使用的是Windows，并没有考虑到Mac的情况，这里使用的自动化库是pyautogui，mac上的点击/识图等都有些特殊，您可以参考[网站1](https://blog.csdn.net/qq_34495095/article/details/124046211), [网站2](https://www.jianshu.com/p/5e2d4ea6ebb3)等来做相应的调整，如果仍然有问题那估计要您自行调试解决了。
另外微信小程序的小红书暂时抓不到包，本程序现处于不可用状态。
